### ISSUE TITLE
How to retrain the yolov5 with our dataset in matlab?

### ISSUE THREAD

**Issue by chdzhang** [matlab-deep-learning/Pretrained-YOLOX-Network-For-Object-Detection#1]
Thanks for your sharing.

The yolov5.onxs using in matlab is different from yolov2, so how to retrain the model on our dataset?
Can you give a example?

Thanks.

**Comment by viakkala** [comment]
Thanks for reaching out to us. Unfortunately we don't provide API similar to trainYOLOv2Objector that can be used to train YOLO v5 networks. You should be writing a custom training loop to train YOLO v5 which will be similar to the steps mentioned in [Object Detection Using YOLO v3 Deep Learning](https://in.mathworks.com/help/vision/ug/object-detection-using-yolo-v3-deep-learning.html).
