### ISSUE TITLE
Error with R2023b 

### ISSUE THREAD

**Issue by shc33** [matlab-deep-learning/Pretrained-YOLOX-Network-For-Object-Detection#2]
Hello,
When I was trying to run your program in R2023b, the follwong code raised an error message as follows:
--------------------------------------------
model = helper.downloadPretrainedYoloX('yolox_s');
net = model.net;
--------------------------------------------
net = 
Dot indexing is not supported for variables of this type.
Error in dlnetwork/isQuantized (line 1417)
            b = this.PrivateNetwork.isQuantized();
Error in deep.internal.quantization.QuantizedNetworkDisplay/mixinQuantizedNetworkHeader (line 23)
                strategy = net.getStrategy(isQuantized(net));
Error in dlnetwork/getHeader (line 1427)
            header = this.mixinQuantizedNetworkHeader(header, className);
------------------------------------------

**Comment by viakkala** [comment]
The issue has been resolved and the README has been updated. Follow the steps mentioned in the README to infer the yolox models.

**Comment by shc33** [comment]
It works now in R2023b.
Thank you very much.
