### ISSUE TITLE
Demo not working in MATLAB R2023b

### ISSUE THREAD

**Issue by robert-dobre** [matlab-deep-learning/Pretrained-YOLOX-Network-For-Object-Detection#3]
This does not work in R2023b.

Here's the output:

Pretrained yolox_s network (mat file) already exists.
Warning: While loading an object of class 'dlnetwork':
Invalid network.

Error in [dlnetwork](matlab:matlab.internal.language.introspective.errorDocCallback('dlnetwork', 'D:\Program Files\MATLAB\R2023b\toolbox\nnet\cnn\dlnetwork.m', 210)) ([line 210](matlab: opentoline('D:\Program Files\MATLAB\R2023b\toolbox\nnet\cnn\dlnetwork.m',210,0)))
                net = initialize(net, dlX{:});

Error in [dlnetwork.loadobj](matlab:matlab.internal.language.introspective.errorDocCallback('dlnetwork.loadobj', 'D:\Program Files\MATLAB\R2023b\toolbox\nnet\cnn\dlnetwork.m', 992)) ([line 992](matlab: opentoline('D:\Program Files\MATLAB\R2023b\toolbox\nnet\cnn\dlnetwork.m',992,0)))
                    net = dlnetwork(in.LayerGraph, exampleInputs{:}, 'Initialize', in.Initialized);

Error in [helper.downloadPretrainedYoloX](matlab:matlab.internal.language.introspective.errorDocCallback('helper.downloadPretrainedYoloX', 'D:\Program Files\MATLAB\Pretrained-YOLOX-Network-For-Object-Detection-main\src\+helper\downloadPretrainedYoloX.m', 35)) ([line 35](matlab: opentoline('D:\Program Files\MATLAB\Pretrained-YOLOX-Network-For-Object-Detection-main\src\+helper\downloadPretrainedYoloX.m',35,0)))
model = load(netMatFileFullPath);

Error in [LiveEditorEvaluationHelperE260246633](matlab:matlab.internal.language.introspective.errorDocCallback('LiveEditorEvaluationHelperE260246633', 'C:\Users\robert.dobre\AppData\Local\Temp\Editor_sqhhv\LiveEditorEvaluationHelperE260246633.m', 3)) ([line 3](matlab: opentoline('C:\Users\robert.dobre\AppData\Local\Temp\Editor_sqhhv\LiveEditorEvaluationHelperE260246633.m',3,0)))
model = helper.downloadPretrainedYoloX('yolox_s');

Caused by:
    Layer 'outputOutput': Error using the predict function in layer nnet.onnx.layer.CustomOutputLayer. The function threw an error and could not be executed.
        Operands to the logical AND (&&) and OR (||) operators must be convertible to logical scalar values. Use the ANY or ALL functions to reduce operands to logical scalar values.
        
        Error in [nnet.onnx.layer.CustomOutputLayer/predict](matlab:matlab.internal.language.introspective.errorDocCallback('nnet.onnx.layer.CustomOutputLayer/predict', 'C:\ProgramData\MATLAB\SupportPackages\R2023b\toolbox\nnet\supportpackages\onnx\+nnet\+onnx\+layer\CustomOutputLayer.m', 34)) ([line 34](matlab: opentoline('C:\ProgramData\MATLAB\SupportPackages\R2023b\toolbox\nnet\supportpackages\onnx\+nnet\+onnx\+layer\CustomOutputLayer.m',34,0)))
                    if all(char(this.DataFormat) == 'U') && this.IsInputForwardONNX
Incorrect number or types of inputs or outputs for function validateAndPrepareForwardInputs.

Error in [dlnetwork/predict](matlab:matlab.internal.language.introspective.errorDocCallback('dlnetwork/predict', 'D:\Program Files\MATLAB\R2023b\toolbox\nnet\cnn\dlnetwork.m', 881)) ([line 881](matlab: opentoline('D:\Program Files\MATLAB\R2023b\toolbox\nnet\cnn\dlnetwork.m',881,0)))
                [~,x,anyDlarrayInputs,anyFormattedDlarray] = validateAndPrepareForwardInputs(net.PrivateNetwork, x, "predict", inputFormats);

Error in [detectYoloX](matlab:matlab.internal.language.introspective.errorDocCallback('detectYoloX', 'D:\Program Files\MATLAB\Pretrained-YOLOX-Network-For-Object-Detection-main\detectYoloX.m', 41)) ([line 41](matlab: opentoline('D:\Program Files\MATLAB\Pretrained-YOLOX-Network-For-Object-Detection-main\detectYoloX.m',41,0)))
features = predict(dlnet, XTest);

**Comment by khan-tahir** [comment]
Use MATLAB's debugging tools to step through your code and identify the specific line or conditions causing the error.

**Comment by viakkala** [comment]
The issue has been resolved and the README has been updated. Follow the steps mentioned in the README to infer the yolox models.
